### ISSUE TITLE
how to find embedded.mobileprovision

### ISSUE THREAD

**Issue by abasakre** [SignTools/altserver-cert-dumper#1]
bro i have windows 10  work for me find p12 and password  but how to find embedded.mobileprovision ?

**Comment by ViRb3** [comment]
You don't need a `.mobileprovision` file if you are using an account (email + password).

**Comment by abasakre** [comment]
but how to add iOS Signer CI and the mobileprovision is required. how to used ?

**Comment by ViRb3** [comment]
Assuming you are using Heroku, if you fill in `PROFILE_ACCOUNT_NAME` and `PROFILE_ACCOUNT_PASS`, you can leave the `PROFILE_PROV_BASE64` empty. Read the description below each setting.
