### ISSUE TITLE
altserver freezes upon opening after replacing the dll

### ISSUE THREAD

**Issue by abdullah5490** [SignTools/altserver-cert-dumper#15]
after I replace that dll and open altserver, a message box appear with the title "success", but it is not responding! I can't click ok, cannot close it, and without doing so, altserver does not appear in system tray from where I can choose to install altstore. I've done almost everything, but this message box always freezes on screen, and only way to close it by ending task "altserver.exe" fourcefully from task manager.
windows11-64bit, latest version of altserver at the time of writing.

**Comment by ViRb3** [comment]
Strange, just tested on AltServer 1.5.1.0 and Windows 11 22H2 22622.450, I get "Success: Hooks initialized", messagebox closes fine, and then AltStore pops up in my tray and works as normal. Do you have any anti-virus program? Try testing this on another computer or VM as I cannot seem to reproduce it.

**Comment by Nigel1992** [comment]
Same issue here.
Running latest AltServer 1.6 as Admin.
Windows 10.

AltServer launches fine, but when trying to install it freezes and crashes.

**Comment by ViRb3** [comment]
Please check my follow-up questions above. I still cannot reproduce this issue.

**Comment by Nigel1992** [comment]
> Please check my follow-up response above. I still cannot reproduce this issue.

Do you have a download link for 1.5.1.0 ?
I cant find it.

**Comment by ViRb3** [comment]
Not needed, just tested again and it works with AltServer 1.6.

**Comment by Nigel1992** [comment]
Alright, thanks for testing.
I'll try some stuff and see if it fixes it.

**Comment by ViRb3** [comment]
Test environment:
```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎11/‎22/‎2022
OS build	22621.819
Experience	Windows Feature Experience Pack 1000.22636.1000.0
```

**Comment by Nigel1992** [comment]
Works after doing a full uninstall with Revo Uninstaller.
Thanks @ViRb3 for your work!
