### ISSUE TITLE
Any way to get a provision file ?

### ISSUE THREAD

**Issue by Nigel1992** [SignTools/altserver-cert-dumper#20]
I managed to get the .p12 file, but E-Sign requires p12 and the provision file.
Windows 10.
Free Developer Cert.

![image](https://user-images.githubusercontent.com/5491930/217018455-93c00312-048d-4d48-ad5a-d2d33d1a3598.png)

**Comment by ViRb3** [comment]
This tool was created specifically for SignTools, not anything else, so I'm afraid I can't provide support. It's technically possible to extract the provision file, but it won't be trivial and I can't assist you.
